# Generated by Django 5.2.5 on 2025-08-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=99)),
                ('subject', models.CharField(max_length=99)),
                ('message', models.TextField(max_length=499)),
            ],
        ),
    ]
